spring:
  application:
    name: FirstProject

  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:${user.dir}/data/demo.db

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
